import os
from .translation_service import localize_report

class MarketReportAgent:
    """
    Synthesizes the swarm intelligence behavior into a localized prediction.
    """
    def __init__(self, language="English"):
        # The language is now passed from user settings
        self.language = language

    def generate_prediction_report(self, simulation_results: list):
        """
        Processes agent interactions into a final market outlook.
        """
        # Base report generated by the engine
        raw_report = {
            "title": "Trading Swarm Forecast",
            "summary": "High-volume 'Whale' movement detected. Retail sentiment is trending bearish.",
            "sentiment_score": -0.75,
            "prediction": "Downside risk prevalent in the next 3 trading cycles."
        }
        
        # Apply the Global Localization layer
        return localize_report(raw_report, self.language)

def get_localized_report(results, target_lang="English"):
    """Entry point for the frontend to request a report in a specific language."""
    agent = MarketReportAgent(language=target_lang)
    return agent.generate_prediction_report(results)
